static uint8_t keycode_map[256];

void init_keycode_map() {
  for (int i = 0; i < sizeof(keycode_map) / sizeof(keycode_map[0]); i++) {
    keycode_map[i] = AMIGA_KEYCODE_NOT_A_KEY;
  }
  keycode_map[PC_KEYCODE_ESC] = AMIGA_KEYCODE_ESC;
  keycode_map[PC_KEYCODE_F1] = AMIGA_KEYCODE_F1;
  keycode_map[PC_KEYCODE_F2] = AMIGA_KEYCODE_F2;
  keycode_map[PC_KEYCODE_F3] = AMIGA_KEYCODE_F3;
  keycode_map[PC_KEYCODE_F4] = AMIGA_KEYCODE_F4;
  keycode_map[PC_KEYCODE_F5] = AMIGA_KEYCODE_F5;
  keycode_map[PC_KEYCODE_F6] = AMIGA_KEYCODE_F6;
  keycode_map[PC_KEYCODE_F7] = AMIGA_KEYCODE_F7;
  keycode_map[PC_KEYCODE_F8] = AMIGA_KEYCODE_F8;
  keycode_map[PC_KEYCODE_F9] = AMIGA_KEYCODE_F9;
  keycode_map[PC_KEYCODE_F10] = AMIGA_KEYCODE_F10;
  keycode_map[PC_KEYCODE_BACKTICK_TILDE] = AMIGA_KEYCODE_BACKTICK_TILDE;
  keycode_map[PC_KEYCODE_1_EXCLAMATION] = AMIGA_KEYCODE_1_EXCLAMATION;
  keycode_map[PC_KEYCODE_2_AT_SIGN] = AMIGA_KEYCODE_2_AT_SIGN;
  keycode_map[PC_KEYCODE_3_POUND_SIGN] = AMIGA_KEYCODE_3_POUND_SIGN;
  keycode_map[PC_KEYCODE_4_DOLLAR_SIGN] = AMIGA_KEYCODE_4_DOLLAR_SIGN;
  keycode_map[PC_KEYCODE_5_PERCENT] = AMIGA_KEYCODE_5_PERCENT;
  keycode_map[PC_KEYCODE_6_HAT] = AMIGA_KEYCODE_6_HAT;
  keycode_map[PC_KEYCODE_7_AMPERSAND] = AMIGA_KEYCODE_7_AMPERSAND;
  keycode_map[PC_KEYCODE_8_ASTERISK] = AMIGA_KEYCODE_8_ASTERISK;
  keycode_map[PC_KEYCODE_9_OPEN_PARENTHESIS] = AMIGA_KEYCODE_9_OPEN_PARENTHESIS;
  keycode_map[PC_KEYCODE_0_CLOSE_PARENTHESIS] = AMIGA_KEYCODE_0_CLOSE_PARENTHESIS;
  keycode_map[PC_KEYCODE_MINUS_UNDERSCORE] = AMIGA_KEYCODE_MINUS_UNDERSCORE;
  keycode_map[PC_KEYCODE_EQUALS_PLUS] = AMIGA_KEYCODE_EQUALS_PLUS;
  keycode_map[PC_KEYCODE_BACKSLASH_PIPE] = AMIGA_KEYCODE_BACKSLASH_PIPE;
  keycode_map[PC_KEYCODE_BACKSPACE] = AMIGA_KEYCODE_BACKSPACE;

  keycode_map[PC_KEYCODE_TAB] = AMIGA_KEYCODE_TAB;
  keycode_map[PC_KEYCODE_Q] = AMIGA_KEYCODE_Q;
  keycode_map[PC_KEYCODE_W] = AMIGA_KEYCODE_W;
  keycode_map[PC_KEYCODE_E] = AMIGA_KEYCODE_E;
  keycode_map[PC_KEYCODE_R] = AMIGA_KEYCODE_R;
  keycode_map[PC_KEYCODE_T] = AMIGA_KEYCODE_T;
  keycode_map[PC_KEYCODE_Y] = AMIGA_KEYCODE_Y;
  keycode_map[PC_KEYCODE_U] = AMIGA_KEYCODE_U;
  keycode_map[PC_KEYCODE_I] = AMIGA_KEYCODE_I;
  keycode_map[PC_KEYCODE_O] = AMIGA_KEYCODE_O;
  keycode_map[PC_KEYCODE_P] = AMIGA_KEYCODE_P;
  keycode_map[PC_KEYCODE_LEFT_SQUARE_SQUIGLEY_BRACKET] = AMIGA_KEYCODE_LEFT_SQUARE_SQUIGLEY_BRACKET;
  keycode_map[PC_KEYCODE_RIGHT_SQUARE_SQUIGLEY_BRACKET] = AMIGA_KEYCODE_RIGHT_SQUARE_SQUIGLEY_BRACKET;
  keycode_map[PC_KEYCODE_RETURN] = AMIGA_KEYCODE_RETURN;

  keycode_map[PC_KEYCODE_FAKE_CTRL] = AMIGA_KEYCODE_CTRL;
  // keycode_map[PC_KEYCODE_LEFT_CTRL] = AMIGA_KEYCODE_CTRL;
  // keycode_map[PC_KEYCODE_RIGHT_CTRL] = AMIGA_KEYCODE_CTRL;
  keycode_map[PC_KEYCODE_CAPS_LOCK] = AMIGA_KEYCODE_CAPS_LOCK;
  keycode_map[PC_KEYCODE_A] = AMIGA_KEYCODE_A;
  keycode_map[PC_KEYCODE_S] = AMIGA_KEYCODE_S;
  keycode_map[PC_KEYCODE_D] = AMIGA_KEYCODE_D;
  keycode_map[PC_KEYCODE_F] = AMIGA_KEYCODE_F;
  keycode_map[PC_KEYCODE_G] = AMIGA_KEYCODE_G;
  keycode_map[PC_KEYCODE_H] = AMIGA_KEYCODE_H;
  keycode_map[PC_KEYCODE_J] = AMIGA_KEYCODE_J;
  keycode_map[PC_KEYCODE_K] = AMIGA_KEYCODE_K;
  keycode_map[PC_KEYCODE_L] = AMIGA_KEYCODE_L;
  keycode_map[PC_KEYCODE_SEMICOLON_COLON] = AMIGA_KEYCODE_SEMICOLON_COLON;
  keycode_map[PC_KEYCODE_SINGLE_DOUBLE_QUOTE] = AMIGA_KEYCODE_SINGLE_DOUBLE_QUOTE;
  // keycode_map[PC_KEYCODE_I18N_KEY_NEXT_TO_RETURN] = AMIGA_KEYCODE_I18N_KEY_NEXT_TO_RETURN;

  keycode_map[PC_KEYCODE_FAKE_LEFT_SHIFT] = AMIGA_KEYCODE_LEFT_SHIFT;
  // keycode_map[PC_KEYCODE_I18N_KEY_NEXT_TO_LEFT_SHIFT] = AMIGA_KEYCODE_I18N_KEY_NEXT_TO_LEFT_SHIFT;
  keycode_map[PC_KEYCODE_Z] = AMIGA_KEYCODE_Z;
  keycode_map[PC_KEYCODE_X] = AMIGA_KEYCODE_X;
  keycode_map[PC_KEYCODE_C] = AMIGA_KEYCODE_C;
  keycode_map[PC_KEYCODE_V] = AMIGA_KEYCODE_V;
  keycode_map[PC_KEYCODE_B] = AMIGA_KEYCODE_B;
  keycode_map[PC_KEYCODE_N] = AMIGA_KEYCODE_N;
  keycode_map[PC_KEYCODE_M] = AMIGA_KEYCODE_M;
  keycode_map[PC_KEYCODE_COMMA_LESS_THAN] = AMIGA_KEYCODE_COMMA_LESS_THAN;
  keycode_map[PC_KEYCODE_PERIOD_GREATER_THAN] = AMIGA_KEYCODE_PERIOD_GREATER_THAN;
  keycode_map[PC_KEYCODE_SLASH_QUESTION_MARK] = AMIGA_KEYCODE_SLASH_QUESTION_MARK;
  keycode_map[PC_KEYCODE_FAKE_RIGHT_SHIFT] = AMIGA_KEYCODE_RIGHT_SHIFT;

  keycode_map[PC_KEYCODE_FAKE_LEFT_ALT] = AMIGA_KEYCODE_LEFT_ALT;
  keycode_map[PC_KEYCODE_FAKE_LEFT_SUPER] = AMIGA_KEYCODE_LEFT_AMIGA;
  keycode_map[PC_KEYCODE_SPACEBAR] = AMIGA_KEYCODE_SPACEBAR;
  keycode_map[PC_KEYCODE_FAKE_RIGHT_SUPER] = AMIGA_KEYCODE_RIGHT_AMIGA;
  keycode_map[PC_KEYCODE_FAKE_RIGHT_ALT] = AMIGA_KEYCODE_RIGHT_ALT;

  keycode_map[PC_KEYCODE_DEL] = AMIGA_KEYCODE_DEL;
  keycode_map[PC_KEYCODE_F12] = AMIGA_KEYCODE_HELP;  // F12 => Help

  keycode_map[PC_KEYCODE_CURSOR_UP] = AMIGA_KEYCODE_CURSOR_UP;
  keycode_map[PC_KEYCODE_CURSOR_LEFT] = AMIGA_KEYCODE_CURSOR_LEFT;
  keycode_map[PC_KEYCODE_CURSOR_DOWN] = AMIGA_KEYCODE_CURSOR_DOWN;
  keycode_map[PC_KEYCODE_CURSOR_RIGHT] = AMIGA_KEYCODE_CURSOR_RIGHT;

  // keycode_map[PC_KEYCODE_NUMERIC_OPEN_PARENTHESIS] = AMIGA_KEYCODE_NUMERIC_OPEN_PARENTHESIS;
  // keycode_map[PC_KEYCODE_NUMERIC_CLOSE_PARENTHESIS] = AMIGA_KEYCODE_NUMERIC_CLOSE_PARENTHESIS;
  keycode_map[PC_KEYCODE_NUMERIC_SLASH] = AMIGA_KEYCODE_NUMERIC_SLASH;
  keycode_map[PC_KEYCODE_NUMERIC_ASTERISK] = AMIGA_KEYCODE_NUMERIC_ASTERISK;

  keycode_map[PC_KEYCODE_NUMERIC_7_HOME] = AMIGA_KEYCODE_NUMERIC_7;
  keycode_map[PC_KEYCODE_NUMERIC_8_CURSOR_UP] = AMIGA_KEYCODE_NUMERIC_8;
  keycode_map[PC_KEYCODE_NUMERIC_9_PAGE_UP] = AMIGA_KEYCODE_NUMERIC_9;
  keycode_map[PC_KEYCODE_NUMERIC_MINUS] = AMIGA_KEYCODE_NUMERIC_MINUS;
  keycode_map[PC_KEYCODE_NUMERIC_4_CURSOR_LEFT] = AMIGA_KEYCODE_NUMERIC_4;

  keycode_map[PC_KEYCODE_NUMERIC_5] = AMIGA_KEYCODE_NUMERIC_5;
  keycode_map[PC_KEYCODE_NUMERIC_6_CURSOR_RIGHT] = AMIGA_KEYCODE_NUMERIC_6;
  keycode_map[PC_KEYCODE_NUMERIC_PLUS] = AMIGA_KEYCODE_NUMERIC_PLUS;

  keycode_map[PC_KEYCODE_NUMERIC_1_END] = AMIGA_KEYCODE_NUMERIC_1;
  keycode_map[PC_KEYCODE_NUMERIC_2_CUROR_DOWN] = AMIGA_KEYCODE_NUMERIC_2;
  keycode_map[PC_KEYCODE_NUMERIC_3_PAGE_DOWN] = AMIGA_KEYCODE_NUMERIC_3;
  keycode_map[PC_KEYCODE_NUMERIC_ENTER] = AMIGA_KEYCODE_NUMERIC_ENTER;

  keycode_map[PC_KEYCODE_NUMERIC_0_INSERT] = AMIGA_KEYCODE_NUMERIC_0;
  keycode_map[PC_KEYCODE_NUMERIC_PERIOD] = AMIGA_KEYCODE_NUMERIC_PERIOD;
};
